"""
Export Service — Generate PDF and text exports from rich summary output.

Uses fpdf2 (pure Python, free, no system dependencies).
"""

import io
from typing import Optional


def format_as_text(summary: str, rich_output: Optional[dict] = None) -> str:
    """Format summary + rich output as plain text."""
    lines = []

    if rich_output and rich_output.get("tldr"):
        lines.append(f"TL;DR: {rich_output['tldr']}")
        lines.append("")

    lines.append("=" * 60)
    lines.append("SUMMARY")
    lines.append("=" * 60)
    lines.append(summary)
    lines.append("")

    if rich_output:
        takeaways = rich_output.get("key_takeaways", [])
        if takeaways:
            lines.append("-" * 40)
            lines.append("KEY TAKEAWAYS")
            lines.append("-" * 40)
            for i, t in enumerate(takeaways, 1):
                lines.append(f"  {i}. {t}")
            lines.append("")

        chapters = rich_output.get("chapters", [])
        if chapters:
            lines.append("-" * 40)
            lines.append("CHAPTERS")
            lines.append("-" * 40)
            for i, ch in enumerate(chapters, 1):
                title = ch.get("title", f"Chapter {i}")
                text = ch.get("text", "")
                lines.append(f"\n  {i}. {title}")
                lines.append(f"     {text}")
            lines.append("")

        quotes = rich_output.get("best_quotes", [])
        if quotes:
            lines.append("-" * 40)
            lines.append("BEST QUOTES")
            lines.append("-" * 40)
            for q in quotes:
                text = q.get("text", "")
                speaker = q.get("speaker", "")
                attribution = f" — {speaker}" if speaker else ""
                lines.append(f'  "{text}"{attribution}')
            lines.append("")

        who_watch = rich_output.get("who_should_watch", "")
        who_skip = rich_output.get("who_can_skip", "")
        if who_watch or who_skip:
            lines.append("-" * 40)
            if who_watch:
                lines.append(f"WHO SHOULD WATCH: {who_watch}")
            if who_skip:
                lines.append(f"WHO CAN SKIP: {who_skip}")
            lines.append("")

        steps = rich_output.get("action_steps", [])
        if steps:
            lines.append("-" * 40)
            lines.append("ACTION STEPS")
            lines.append("-" * 40)
            for i, s in enumerate(steps, 1):
                lines.append(f"  {i}. {s}")
            lines.append("")

    lines.append("=" * 60)
    lines.append("Generated by AI Video Summarizer")
    lines.append("=" * 60)

    return "\n".join(lines)


def generate_pdf(summary: str, rich_output: Optional[dict] = None) -> bytes:
    """Generate a PDF from summary + rich output. Returns PDF bytes."""
    from fpdf import FPDF

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, "AI Video Summary", new_x="LMARGIN", new_y="NEXT", align="C")
    pdf.ln(6)

    # TL;DR
    if rich_output and rich_output.get("tldr"):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "TL;DR", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(60, 60, 60)
        pdf.multi_cell(0, 6, rich_output["tldr"])
        pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

    # Summary
    pdf.set_font("Helvetica", "B", 13)
    pdf.cell(0, 10, "Summary", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 6, summary)
    pdf.ln(4)

    if rich_output:
        # Key Takeaways
        takeaways = rich_output.get("key_takeaways", [])
        if takeaways:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Key Takeaways", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for i, t in enumerate(takeaways, 1):
                pdf.multi_cell(0, 6, f"  {i}. {t}")
            pdf.ln(4)

        # Chapters
        chapters = rich_output.get("chapters", [])
        if chapters:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Chapters", new_x="LMARGIN", new_y="NEXT")
            for i, ch in enumerate(chapters, 1):
                pdf.set_font("Helvetica", "B", 10)
                pdf.cell(0, 7, f"  {i}. {ch.get('title', '')}", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 9)
                pdf.set_text_color(80, 80, 80)
                pdf.multi_cell(0, 5, f"     {ch.get('text', '')}")
                pdf.set_text_color(0, 0, 0)
            pdf.ln(4)

        # Best Quotes
        quotes = rich_output.get("best_quotes", [])
        if quotes:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Best Quotes", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "I", 10)
            for q in quotes:
                text = q.get("text", "")
                speaker = q.get("speaker", "")
                line = f'  "{text}"'
                if speaker:
                    line += f" - {speaker}"
                pdf.multi_cell(0, 6, line)
            pdf.set_font("Helvetica", "", 10)
            pdf.ln(4)

        # Action Steps
        steps = rich_output.get("action_steps", [])
        if steps:
            pdf.set_font("Helvetica", "B", 13)
            pdf.cell(0, 10, "Action Steps", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "", 10)
            for i, s in enumerate(steps, 1):
                pdf.multi_cell(0, 6, f"  {i}. {s}")
            pdf.ln(4)

    # Footer
    pdf.ln(8)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 6, "Generated by AI Video Summarizer", align="C")

    return pdf.output()
